### ISSUE TITLE
Release v0.1.4 crashes on windows

### ISSUE THREAD

**Issue by matiasba** [kayrus/gof5#39]
Version 0.1.4 crashes when creating tunnel on windows. I will attach the runtime stack:

```
>gof5_windows_amd64.exe -server [redacted] -username [redacted]
2021/12/02 15:18:03 gof5 v0.1.4-dev compiled with go1.17.2 for windows/amd64
2021/12/02 15:18:03 Reusing saved HTTPS VPN session for [redacted]
2021/12/02 15:18:03 Found F5 VPN profiles: ["0:/Common/[redacted]"]
2021/12/02 15:18:03 Using "[redacted]" F5 VPN profile
2021/12/02 15:18:03 MTU: 1396
2021/12/02 15:18:03 Magic: e122bec1
2021/12/02 15:18:03 PFC: 0702
2021/12/02 15:18:03 ACFC: 0802
2021/12/02 15:18:03 id: 1, IPV6 accepted
2021/12/02 15:18:03 id: 2, MTU accepted
2021/12/02 15:18:03 id: 1, id2: 3, Remote IPv4 requested: [redacted]
2021/12/02 15:18:03 id: 1, id2: 1, Remote IPv6 requested: [redacted]
2021/12/02 15:18:03 id: 1, id2: 3, Local IPv4 not acknowledged: [redacted]
2021/12/02 15:18:03 id: 1, id2: 3, Local IPv4 acknowledged: [redacted]
2021/12/02 15:18:03 Using wireguard module to create tunnel
runtime: bad pointer in frame golang.zx2c4.com/wireguard/tun/wintun.logMessage at 0xc00009d558: 0x20
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw({0x5d1f98, 0x902460})
        runtime/panic.go:1198 +0x76 fp=0xece9dfd248 sp=0xece9dfd218 pc=0x1366d6
runtime.adjustpointers(0xece9dfd668, 0x0, 0x8cc768, {0x8cc768, 0x902460})
        runtime/stack.go:617 +0x1d0 fp=0xece9dfd2b0 sp=0xece9dfd248 pc=0x14b290
runtime.adjustframe(0xece9dfd668, 0xece9dfd750)
        runtime/stack.go:659 +0xcc fp=0xece9dfd360 sp=0xece9dfd2b0 pc=0x14b3ac
runtime.gentraceback(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x5e9d40, 0x0, 0x0)
        runtime/traceback.go:350 +0xac3 fp=0xece9dfd6d0 sp=0xece9dfd360 pc=0x1565e3
runtime.copystack(0xc000388000, 0x4000)
        runtime/stack.go:918 +0x293 fp=0xece9dfd880 sp=0xece9dfd6d0 pc=0x14bb73
runtime.newstack()
        runtime/stack.go:1097 +0x48f fp=0xece9dfda30 sp=0xece9dfd880 pc=0x14c0ef
runtime.morestack()
        runtime/asm_amd64.s:461 +0x93 fp=0xece9dfda38 sp=0xece9dfda30 pc=0x1620d3

goroutine 40 [copystack, locked to thread]:
runtime.mapaccess1_fast32(0x550180, 0x0, 0x48420)
        runtime/map_fast32.go:12 +0x17d fp=0xc00009d370 sp=0xc00009d368 pc=0x1105fd
runtime.resolveTypeOff(0x0, 0x48420)
        runtime/type.go:246 +0x85 fp=0xc00009d3c8 sp=0xc00009d370 pc=0x159ee5
runtime.(*_type).typeOff(...)
        runtime/type.go:258
runtime.(*itab).init(0x23939f0bc98)
        runtime/iface.go:209 +0x105 fp=0xc00009d478 sp=0xc00009d3c8 pc=0x10a305
runtime.getitab(0x5597e0, 0x5b74e0, 0x1)
        runtime/iface.go:75 +0x136 fp=0xc00009d4c0 sp=0xc00009d478 pc=0x109e36
runtime.assertI2I2(0x0, {0x665040, 0xc000006020})
        runtime/iface.go:467 +0x3d fp=0xc00009d4f0 sp=0xc00009d4c0 pc=0x10ae9d
golang.zx2c4.com/wireguard/tun/wintun.logMessage(0xc000034000, 0xece9dfe3c0, 0x1040e8)
        golang.zx2c4.com/wireguard@v0.0.0-20211028114750-eb6302c7eb71/tun/wintun/wintun_windows.go:46 +0x51 fp=0xc00009d580 sp=0xc00009d4f0 pc=0x45a8d1
runtime.call32(0x0, 0x5e9988, 0xc00014b618, 0x0, 0x0, 0x18, 0xc00014b870)
        runtime/asm_amd64.s:626 +0x50 fp=0xc00009d5b0 sp=0xc00009d580 pc=0x162590
runtime.callbackWrap(0xece9dfda70)
        runtime/syscall_windows.go:378 +0x134 fp=0xc00009d990 sp=0xc00009d5b0 pc=0x151854
runtime.cgocallbackg1(0x151720, 0xc000100400, 0x0)
        runtime/cgocall.go:306 +0x29a fp=0xc00009da60 sp=0xc00009d990 pc=0x10459a
runtime.cgocallbackg(0xc000388000, 0x300000002, 0xc000388000)
        runtime/cgocall.go:232 +0x106 fp=0xc00009daf8 sp=0xc00009da60 pc=0x104226
runtime.cgocallbackg(0x151720, 0xece9dfda70, 0x0)
        <autogenerated>:1 +0x36 fp=0xc00009db20 sp=0xc00009daf8 pc=0x166296
runtime.cgocallback(0x1040ac, 0x165ba0, 0xc0001006e0)
        runtime/asm_amd64.s:915 +0xd7 fp=0xc00009db48 sp=0xc00009db20 pc=0x1640d7
runtime.systemstack_switch()
        runtime/asm_amd64.s:350 fp=0xc00009db50 sp=0xc00009db48 pc=0x161f80
runtime.cgocall(0x165ba0, 0xc0001006e0)
        runtime/cgocall.go:166 +0xac fp=0xc00009db88 sp=0xc00009db50 pc=0x1040ac
syscall.Syscall(0x7ffacd286100, 0x3, 0xc000021d54, 0xc000022d98, 0x0)
        runtime/syscall_windows.go:479 +0xf4 fp=0xc00009dbc0 sp=0xc00009db88 pc=0x1607d4
syscall.Syscall(0xc000198fc0, 0x0, 0x1e1440, 0xc0000bc6c0, 0x1e14a0)
        <autogenerated>:1 +0x2b fp=0xc00009dc10 sp=0xc00009dbc0 pc=0x166a8b
golang.zx2c4.com/wireguard/tun/wintun.CreateAdapter({0x5c325f, 0x2021e6}, {0x5c4e17, 0x9}, 0x0)
        golang.zx2c4.com/wireguard@v0.0.0-20211028114750-eb6302c7eb71/tun/wintun/wintun_windows.go:90 +0x10d fp=0xc00009dc98 sp=0xc00009dc10 pc=0x45ac4d
golang.zx2c4.com/wireguard/tun.CreateTUNWithRequestedGUID({0x5c325f, 0xa0}, 0x10d134, 0x574)
        golang.zx2c4.com/wireguard@v0.0.0-20211028114750-eb6302c7eb71/tun/tun_windows.go:71 +0x46 fp=0xc00009dd10 sp=0xc00009dc98 pc=0x45b946
golang.zx2c4.com/wireguard/tun.CreateTUN(...)
        golang.zx2c4.com/wireguard@v0.0.0-20211028114750-eb6302c7eb71/tun/tun_windows.go:63
github.com/kayrus/tuncfg/tun.OpenTunDevice(0x5d7975, 0x0, {0x5c325f, 0x0}, 0x0)
        github.com/kayrus/tuncfg@v0.0.0-20211029100448-15eab7b00382/tun/tun.go:17 +0x78 fp=0xc00009ddd0 sp=0xc00009dd10 pc=0x45cb78
github.com/kayrus/gof5/pkg/link.(*vpnLink).createTunDevice(0xc000296240)
        github.com/kayrus/gof5/pkg/link/link.go:184 +0x22e fp=0xc00009de80 sp=0xc00009ddd0 pc=0x4b692e
github.com/kayrus/gof5/pkg/link.(*vpnLink).WaitAndConfig(0xc000296240, 0xc0000d8580)
        github.com/kayrus/gof5/pkg/link/link.go:288 +0xe5 fp=0xc00009dfc0 sp=0xc00009de80 pc=0x4b73e5
github.com/kayrus/gof5/pkg/client.Connect·dwrap·3()
        github.com/kayrus/gof5/pkg/client/client.go:177 +0x2a fp=0xc00009dfe0 sp=0xc00009dfc0 pc=0x4ff6ea
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc00009dfe8 sp=0xc00009dfe0 pc=0x164301
created by github.com/kayrus/gof5/pkg/client.Connect
        github.com/kayrus/gof5/pkg/client/client.go:177 +0x1214

goroutine 1 [select]:
runtime.gopark(0xc0000bbe88, 0x3, 0x68, 0xba, 0xc0000bbbda)
        runtime/proc.go:366 +0xd6 fp=0xc0000bba38 sp=0xc0000bba18 pc=0x139036
runtime.selectgo(0xc0000bbe88, 0xc0000bbbd4, 0x4, 0x0, 0x21, 0x1)
        runtime/select.go:327 +0x792 fp=0xc0000bbb80 sp=0xc0000bba38 pc=0x146ff2
github.com/kayrus/gof5/pkg/client.Connect(0xc0000c0100)
        github.com/kayrus/gof5/pkg/client/client.go:232 +0x190f fp=0xc0000bbf08 sp=0xc0000bbb80 pc=0x4ff0cf
main.main()
        github.com/kayrus/gof5/cmd/gof5/main.go:64 +0x4cf fp=0xc0000bbf80 sp=0xc0000bbf08 pc=0x503dcf
runtime.main()
        runtime/proc.go:255 +0x217 fp=0xc0000bbfe0 sp=0xc0000bbf80 pc=0x138c97
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc0000bbfe8 sp=0xc0000bbfe0 pc=0x164301

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
        runtime/proc.go:366 +0xd6 fp=0xc000073fb0 sp=0xc000073f90 pc=0x139036
runtime.goparkunlock(...)
        runtime/proc.go:372
runtime.forcegchelper()
        runtime/proc.go:306 +0xb1 fp=0xc000073fe0 sp=0xc000073fb0 pc=0x138ed1
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0x164301
created by runtime.init.7
        runtime/proc.go:294 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
        runtime/proc.go:366 +0xd6 fp=0xc000075fb0 sp=0xc000075f90 pc=0x139036
runtime.goparkunlock(...)
        runtime/proc.go:372
runtime.bgsweep()
        runtime/mgcsweep.go:163 +0x88 fp=0xc000075fe0 sp=0xc000075fb0 pc=0x122f08
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc000075fe8 sp=0xc000075fe0 pc=0x164301
created by runtime.gcenable
        runtime/mgc.go:181 +0x55

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
        runtime/proc.go:366 +0xd6 fp=0xc000085f80 sp=0xc000085f60 pc=0x139036
runtime.goparkunlock(...)
        runtime/proc.go:372
runtime.bgscavenge()
        runtime/mgcscavenge.go:265 +0xcd fp=0xc000085fe0 sp=0xc000085f80 pc=0x12100d
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc000085fe8 sp=0xc000085fe0 pc=0x164301
created by runtime.gcenable
        runtime/mgc.go:182 +0x65

goroutine 5 [finalizer wait]:
runtime.gopark(0x1393d2, 0xc000077f70, 0xb1, 0x53, 0x8fce60)
        runtime/proc.go:366 +0xd6 fp=0xc000077e30 sp=0xc000077e10 pc=0x139036
runtime.goparkunlock(...)
        runtime/proc.go:372
runtime.runfinq()
        runtime/mfinal.go:177 +0xb3 fp=0xc000077fe0 sp=0xc000077e30 pc=0x118993
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc000077fe8 sp=0xc000077fe0 pc=0x164301
created by runtime.createfing
        runtime/mfinal.go:157 +0x45

goroutine 39 [syscall]:
runtime.notetsleepg(0x13fd25, 0xc0002a01a0)
        runtime/lock_sema.go:295 +0x3c fp=0xc000081fa0 sp=0xc000081f58 pc=0x10bbdc
os/signal.signal_recv()
        runtime/sigqueue.go:169 +0x98 fp=0xc000081fc0 sp=0xc000081fa0 pc=0x15fad8
os/signal.loop()
        os/signal/signal_unix.go:24 +0x19 fp=0xc000081fe0 sp=0xc000081fc0 pc=0x37e199
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc000081fe8 sp=0xc000081fe0 pc=0x164301
created by os/signal.Notify.func1.1
        os/signal/signal.go:151 +0x2c

goroutine 41 [IO wait]:
runtime.gopark(0x0, 0xc0002b4518, 0xc8, 0x45, 0xc0002b4548)
        runtime/proc.go:366 +0xd6 fp=0xc000399788 sp=0xc000399768 pc=0x139036
runtime.netpollblock(0xa, 0x2b4558, 0xc0)
        runtime/netpoll.go:445 +0xde fp=0xc0003997c0 sp=0xc000399788 pc=0x12f1de
internal/poll.runtime_pollWait(0x23939f02988, 0x72)
        runtime/netpoll.go:229 +0x89 fp=0xc0003997e0 sp=0xc0003997c0 pc=0x15de89
internal/poll.(*pollDesc).wait(0x10, 0xd, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc000399808 sp=0xc0003997e0 pc=0x1ddb72
internal/poll.execIO(0xc0002b4518, 0x5e99d0)
        internal/poll/fd_windows.go:175 +0xe5 fp=0xc000399860 sp=0xc000399808 pc=0x1df1a5
internal/poll.(*FD).Read(0xc0002b4500, {0xc0002dc000, 0x177a, 0x177a})
        internal/poll/fd_windows.go:441 +0x25f fp=0xc0003998f0 sp=0xc000399860 pc=0x1dffbf
net.(*netFD).Read(0xc0002b4500, {0xc0002dc000, 0xc0002dc00d, 0x2})
        net/fd_posix.go:56 +0x29 fp=0xc000399938 sp=0xc0003998f0 pc=0x28e149
net.(*conn).Read(0xc00029a158, {0xc0002dc000, 0x176d, 0xc000399a18})
        net/net.go:183 +0x45 fp=0xc000399980 sp=0xc000399938 pc=0x29d425
net.(*TCPConn).Read(0xc00029a158, {0xc0002dc000, 0x6, 0x100000000000002})
        <autogenerated>:1 +0x2e fp=0xc0003999b0 sp=0xc000399980 pc=0x2a980e
crypto/tls.(*atLeastReader).Read(0xc000284ab0, {0xc0002dc000, 0x0, 0x109d6d})
        crypto/tls/conn.go:777 +0x3d fp=0xc0003999f8 sp=0xc0003999b0 pc=0x2d491d
bytes.(*Buffer).ReadFrom(0xc0002d2278, {0x664720, 0xc000284ab0})
        bytes/buffer.go:204 +0x98 fp=0xc000399a50 sp=0xc0003999f8 pc=0x179678
crypto/tls.(*Conn).readFromUntil(0xc0002d2000, {0x23939f02a70, 0xc00029a158}, 0xc00028fa40)
        crypto/tls/conn.go:799 +0xe5 fp=0xc000399a90 sp=0xc000399a50 pc=0x2d4b05
crypto/tls.(*Conn).readRecordOrCCS(0xc0002d2000, 0x0)
        crypto/tls/conn.go:606 +0x112 fp=0xc000399e38 sp=0xc000399a90 pc=0x2d2172
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc0002d2000, {0xc000282ea8, 0x2, 0x559be0})
        crypto/tls/conn.go:1277 +0x16f fp=0xc000399ea8 sp=0xc000399e38 pc=0x2d7a0f
io.ReadAtLeast({0x2393a320158, 0xc0002d2000}, {0xc000282ea8, 0x2, 0x2}, 0x2)
        io/io.go:328 +0x9a fp=0xc000399ef0 sp=0xc000399ea8 pc=0x1714ba
io.ReadFull(...)
        io/io.go:347
github.com/kayrus/gof5/pkg/link.fromF5(0xc000296240, 0x0)
        github.com/kayrus/gof5/pkg/link/f5.go:434 +0x7d fp=0xc000399f90 sp=0xc000399ef0 pc=0x4b469d
github.com/kayrus/gof5/pkg/link.(*vpnLink).HttpToTun(0xc000296240)
        github.com/kayrus/gof5/pkg/link/f5.go:472 +0x4d fp=0xc000399fc8 sp=0xc000399f90 pc=0x4b4a2d
github.com/kayrus/gof5/pkg/client.Connect·dwrap·10()
        github.com/kayrus/gof5/pkg/client/client.go:226 +0x26 fp=0xc000399fe0 sp=0xc000399fc8 pc=0x4ff446
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc000399fe8 sp=0xc000399fe0 pc=0x164301
created by github.com/kayrus/gof5/pkg/client.Connect
        github.com/kayrus/gof5/pkg/client/client.go:226 +0x1805

goroutine 42 [select]:
runtime.gopark(0xc00038ff78, 0x2, 0x0, 0x0, 0xc00038ff3c)
        runtime/proc.go:366 +0xd6 fp=0xc00038fda8 sp=0xc00038fd88 pc=0x139036
runtime.selectgo(0xc00038ff78, 0xc00038ff38, 0x0, 0x0, 0x0, 0x1)
        runtime/select.go:327 +0x792 fp=0xc00038fef0 sp=0xc00038fda8 pc=0x146ff2
github.com/kayrus/gof5/pkg/link.(*vpnLink).TunToHTTP(0xc000296240)
        github.com/kayrus/gof5/pkg/link/f5.go:543 +0xb4 fp=0xc00038ffc8 sp=0xc00038fef0 pc=0x4b5154
github.com/kayrus/gof5/pkg/client.Connect·dwrap·11()
        github.com/kayrus/gof5/pkg/client/client.go:229 +0x26 fp=0xc00038ffe0 sp=0xc00038ffc8 pc=0x4ff3e6
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc00038ffe8 sp=0xc00038ffe0 pc=0x164301
created by github.com/kayrus/gof5/pkg/client.Connect
        github.com/kayrus/gof5/pkg/client/client.go:229 +0x184f
```

**Comment by kayrus** [comment]
Try to install recent wintun driver: https://www.wintun.net/
There were some incompatible changes between wintun go bindings and recent wintun driver

**Comment by matiasba** [comment]
That did the trick! Thank you man 👍
